apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-read-data-storage-argo-events
  namespace: argo-events
---
# Define a Role to read secrets in the source namespace (data-storage)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: data-storage
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
# Bind the Argo Events SA to that Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets-argo-events-binding
  namespace: data-storage
subjects:
- kind: ServiceAccount
  name: sa-read-data-storage-argo-events
  namespace: argo-events
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io