apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-details
  namespace: argo-events
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store-read-data-storage-argo-events # <--- CHANGED
    kind: SecretStore                                # <--- CHANGED (was ClusterSecretStore)
  target:
    name: minio-details
  data:
    - secretKey: accesskey
      remoteRef:
        key: minio-details
        property: root# filepath: infrastructure/external-secrets/minio-ext-secret-argo-events.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-details
  namespace: argo-events
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store-read-data-storage-argo-events # <--- CHANGED
    kind: SecretStore                                # <--- CHANGED (was ClusterSecretStore)
  target:
    name: minio-details
  data:
    - secretKey: accesskey
      remoteRef:
        key: minio-details
        property: root