apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-deploy-role
  namespace: argo-workflows
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "configmaps"]  # <--- Added configmaps
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-deploy-binding
  namespace: argo-workflows
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    namespace: argo-workflows
roleRef:
  kind: Role
  name: argo-workflow-deploy-role
  apiGroup: rbac.authorization.k8s.io