apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: minio-input
  namespace: argo-events
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    input-data:
      port: "12000"
      endpoint: /input-data
      method: POST